GET http://localhost:3000/api/v0/orders/
###

GET http://localhost:3000/api/v0/orders/O1001
###

GET http://localhost:3000/api/v0/orders/69a8ec1b5db210daf9389c78
###

DELETE http://localhost:3000/api/v0/orders/O1001
###

DELETE http://localhost:3000/api/v0/orders/69a8ec0d6c24683ab3ce1d7a
###

POST http://localhost:3000/api/v0/orders/
content-type: application/json

{
  "orderNumber": 1004,
  "orderDate": "23/05/2022",
  "customerNumber": 8890102345,
  "productCode": "009",
  "productName": "Shampoo",
  "productQuantity": 15,
  "productPrice": 20,
  "totalAmount": 300,
  "modeOfPayment": "Online"
}
###

PATCH http://localhost:3000/api/v0/orders/69a8ec0d6c24683ab3ce1d7a
content-type: application/json

{
  "orderNumber": 1004,
  "orderDate": "23/05/2022",
  "customerNumber": 8890102345,
  "productCode": "009",
  "productName": "Shampoo",
  "productQuantity": 15,
  "productPrice": 20,
  "totalAmount": 300,
  "modeOfPayment": "Online"
}
###

PUT http://localhost:3000/api/v0/orders/O1003
content-type: application/json

{
  "orderNumber": 1004,
  "orderDate": "23/05/2022",
  "customerNumber": 8890102345,
  "productCode": "009",
  "productName": "Shampoo",
  "productQuantity": 15,
  "productPrice": 20,
  "totalAmount": 300,
  "modeOfPayment": "Online"
}
###
