GET http://localhost:3000/api/v0/products/
###

GET http://localhost:3000/api/v0/products/69b005f3bafc3d66a86e4ef9
###

DELETE http://localhost:3000/api/v0/products/69b017c29928ae05e97d5a62
###

POST http://localhost:3000/api/v0/products/
content-type: application/json

{
  "productCode": "008",
  "productName": "Cornflakes",
  "productQuantity": 40,
  "productPrice": 60
}
###

PATCH http://localhost:3000/api/v0/products/69b017d39928ae05e97d5a63
content-type: application/json

{
  "productCode": "888",
  "productName": "Chips",
  "productQuantity": 80,
  "productPrice": 40
}
###

PUT http://localhost:3000/api/v0/products/69b017d39928ae05e97d5a63
content-type: application/json

{
  "productCode": "888",
  "productName": "Chips",
  "productQuantity": 81,
  "productPrice": 41
}
###
